spring:
  application:
    name: BOOKING-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/hotelbooking_booking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Anandrao@6261
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

