spring:
  application:
    name: HOTEL-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/hotelbooking_hotel?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Anandrao@6261
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
app:
  message: "Hello from Config Server - v2"
